user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.articles:
    resource: "@AppBundle/Controller/ArticleController.php"
    type: annotation

app.tags:
    resource: "@AppBundle/Controller/TagController.php"
    type: annotation
    prefix: /tags

app.admin.index:
    resource: "@AppBundle/Controller/Admin/IndexController.php"
    type: annotation
    prefix: /admin

app.admin.tags:
    resource: "@AppBundle/Controller/Admin/TagController.php"
    type: annotation
    prefix: /admin/tags

app.admin.articles:
    resource: "@AppBundle/Controller/Admin/ArticleController.php"
    type: annotation
    prefix: /admin/articles

app.admin.comments:
    resource: "@AppBundle/Controller/Admin/CommentController.php"
    type: annotation
    prefix: /admin/comments

app.comments:
    resource: "@AppBundle/Controller/CommentController.php"
    type: annotation
    prefix: /comment
