user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.articles:
    resource: "@AppBundle/Controller/ArticleController.php"
    type: annotation

app.tags:
    resource: "@AppBundle/Controller/TagController.php"
    type: annotation
    prefix: /tags
