security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        db_users:
            entity:
                class: AppBundle:User
                property: username
                # if I remove property to use the repository I take an error: "Authentication request could not be processed due to a system problem."
                # http://symfony.com/doc/current/cookbook/security/entity_provider.html#security-config-entity-provider

    firewalls:
        main:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: app_security_login
                check_path: app_security_check
                csrf_parameter: _csrf_token
            logout:
                path: app_security_logout
                target: /

    access_control:
#        - { path: ^/update, roles: ROLE_ADMIN  }
#        - { path: ^/remove, roles: ROLE_ADMIN  }