services:
    app.article_voter:
        class: AppBundle\Security\ArticleVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }