services:
    app.article_voter:
        class: AppBundle\Security\ArticleVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        public: false