<?php

namespace AppBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryAllArticles()
    {
        return $this->createQueryBuilder('a')
            ->addOrderBy('a.createdAt', 'DESC')
            ->leftJoin('a.tags', 'tags')
            ->addSelect('tags')
            ->getQuery()
        ;
    }

    public function allArticles()
    {
        return $this->queryAllArticles()->execute();
    }

    public function queryArticlesByTagId($id)
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.tags', 'tags')
            ->addSelect('tags')
            ->addOrderBy('a.createdAt', 'DESC')
            ->andWhere('tags.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
        ;
    }

    public function articlesByTagId($id)
    {
        return $this->queryArticlesByTagId($id)->execute();
    }
}
